In [74]:
#Phonepe Pulse Data Visualization and Exploration
#To import useful modules
import git
import pandas as pd
import os
import json
import pymysql

In [ ]:
#Specify the GitHub repository URL and local directory path
github_url = "https://github.com/PhonePe/pulse.git"
local_dir = "C:/Users/admin pc/Desktop/phonepe_git"

# # Clone the repository to the specified local directory
git.Repo.clone_from(github_url, local_dir)

In [ ]:

#Now i cloned gitHub repository to local directory(C:/Users/admin pc/Desktop/phonepe_git)
#Next have to collect and store the data as Dataframes

In [ ]:
#1)To create aggregated_transaction Dataframe
def create_aggregated_transaction_df():
                path="C:/Users/admin pc/Desktop/phonepe_git/data/aggregated/transaction/country/india/state/"
                AggregationT_transaction_state=os.listdir(path)
                

                #to extact data from json file(state-year-jason)
                aggregated_transaction_data={'State':[], 'Year':[],'Quarter':[],'Transaction_Type':[], 'Transaction_Count':[], 'Transaction_Amount':[]}
                for item1 in AggregationT_transaction_state:
                                path1=path+item1+"/"
                                AggregationT_year_list=os.listdir(path1)
                                for item2 in AggregationT_year_list:
                                        path2=path1+item2+"/"
                                        json_list=os.listdir(path2)
                                        for item3 in json_list:
                                                path3=path2+item3
                                                
                                                read_json=open(path3,"r")
                                                json_file=json.load(read_json)

                                                
                                                for item4 in json_file["data"]["transactionData"]:
                                                                Name=item4["name"]
                                                                Trans_count=item4['paymentInstruments'][0]["count"]
                                                                Trans_amonut=item4['paymentInstruments'][0]["amount"]
                                                                aggregated_transaction_data['Transaction_Type'].append(Name)
                                                                aggregated_transaction_data['Transaction_Count'].append(Trans_count)
                                                                aggregated_transaction_data['Transaction_Amount'].append(Trans_amonut)
                                                                aggregated_transaction_data['State'].append(item1)
                                                                aggregated_transaction_data['Year'].append(item2)
                                                                aggregated_transaction_data['Quarter'].append(int(item3.strip('.json')))

                DATAFRAME1=pd.DataFrame(aggregated_transaction_data)                                               
                return  DATAFRAME1




Dataframe_aggregated_transaction=create_aggregated_transaction_df()

In [ ]:
#2)To create aggregated_user Dataframe
def create_aggregated_user_df():
            
                path="C:/Users/admin pc/Desktop/phonepe_git/data/aggregated/user/country/india/state/"
                Aggregation_User_state=os.listdir(path)
                aggregated_user_data={'State':[], 'Year':[],'Quarter':[],'Brand':[], 'User_Count':[], 'User_Percentage':[]}
            
                for item1 in Aggregation_User_state:
                        path1=path+item1+"/"
                        AggregationU_year_list=os.listdir(path1)
                        for item2 in AggregationU_year_list:
                            path2=path1+item2+"/"
                            json_list=os.listdir(path2)
                            for item3 in json_list:
                                path3=path2+item3
                                
                                read_json=open(path3,"r")
                                json_file=json.load(read_json)

                                try:
                                        
                            
                                    for item4 in json_file["data"]["usersByDevice"]:
                                                brand=item4["brand"]
                                                userCount=item4["count"]
                                                userpercent=item4["percentage"]
                                                aggregated_user_data['State'].append(item1)
                                                aggregated_user_data['Year'].append(item2)
                                                aggregated_user_data['Quarter'].append(int(item3.strip(".json")))
                                                aggregated_user_data['Brand'].append(brand)
                                                aggregated_user_data['User_Count'].append(userCount)
                                                aggregated_user_data['User_Percentage'].append(userpercent*100)
                     
                                except:
                                    pass
                                
                DATAFRAME2=pd.DataFrame(aggregated_user_data)                                               
                return  DATAFRAME2 
          


Dataframe_aggregated_user=create_aggregated_user_df()

In [ ]:
#3)To create_map_transaction Dataframe
def create_map_transaction_df():
          path="C:/Users/admin pc/Desktop/phonepe_git/data/map/transaction/hover/country/india/state/"
          map_transaction_state=os.listdir(path)  

          map_transaction_data={'State':[], 'Year':[],'Quarter':[],'District_Name':[], 'Transaction_Count':[], 'Transaction_Amount':[]}

          for item1 in map_transaction_state:
               path1=path+item1+"/"
               map_transaction_year=os.listdir(path1)
               for item2 in map_transaction_year:
                    path2=path1+item2+"/"
                    json_list=os.listdir(path2)
                    for item3 in json_list:
                         path3=path2+item3
                         
                         read_json=open(path3,"r")
                         json_file=json.load(read_json)

                         for item4 in json_file["data"]["hoverDataList"]:
                              Name=item4["name"]
                              T_Count=item4['metric'][0]["count"]
                              T_Amount=item4['metric'][0]["amount"]
                              map_transaction_data['State'].append(item1)
                              map_transaction_data['Year'].append(item2)
                              map_transaction_data['District_Name'].append(Name)
                              map_transaction_data['Transaction_Count'].append(T_Count)
                              map_transaction_data['Transaction_Amount'].append(T_Amount)
                              map_transaction_data['Quarter'].append(int(item3.strip(".json")))


          df3=pd.DataFrame(map_transaction_data)
          return df3
           
Dataframe_map_transaction=create_map_transaction_df()

In [ ]:
#4)To create_map_user Dataframe
def create_map_user_df():
        path="C:/Users/admin pc/Desktop/phonepe_git/data/map/user/hover/country/india/state/"
        map_user_state=os.listdir(path)

        map_user_data={'State':[], 'Year':[],'Quarter':[],'District_Name':[], 'Registered_Users':[], 'No_of_apps_Open':[]}

        for item1 in map_user_state:
            path1=path+item1+"/"
            map_user_year=os.listdir(path1)
            for item2 in map_user_year:
                path2=path1+item2+"/"
                json_list=os.listdir(path2)
                for item3 in json_list:
                    path3=path2+item3
                    
                    read_json=open(path3,"r")
                    json_file=json.load(read_json)

                    for item4 in json_file["data"]['hoverData'].items():
                        D_name=item4[0]
                        R_user=item4[1]["registeredUsers"]
                        No_of_apps_Open=item4[1]["appOpens"]
                        map_user_data["State"].append(item1)
                        map_user_data["Year"].append(item2)
                        map_user_data["Quarter"].append(int(item3.strip(".json")))
                        map_user_data["District_Name"].append(D_name)
                        map_user_data["Registered_Users"].append(R_user)
                        map_user_data["No_of_apps_Open"].append(No_of_apps_Open)

        df4=pd.DataFrame(map_user_data)
        return df4

Dataframe_map_user=create_map_user_df()

In [ ]:
#5)To create_top_transaction Dataframe
def create_top_transaction_df():
        path="C:/Users/admin pc/Desktop/phonepe_git/data/top/transaction/country/india/state/"
        top_transaction_state=os.listdir(path)

        top_transaction_data={'State':[], 'Year':[],'Quarter':[],'District_pincode':[], 'Transaction_Count':[], 'Transaction_Amount':[]}
        for item1 in top_transaction_state:
            path1=path+item1+"/"
            top_transaction_year=os.listdir(path1)
            for item2 in top_transaction_year:
                path2=path1+item2+"/"
                json_list=os.listdir(path2)
                for item3 in json_list:
                    path3=path2+item3

                    read_json=open(path3,"r")
                    json_file=json.load(read_json)


                    for item4 in json_file["data"]["pincodes"]:
                           D_pincode=item4["entityName"]
                           T_count=item4["metric"]["count"]
                           T_Amount=item4["metric"]["amount"]
                           top_transaction_data["State"].append(item1)
                           top_transaction_data["Year"].append(item2)
                           top_transaction_data["Quarter"].append(int(item3.strip(".json")))
                           top_transaction_data["District_pincode"].append(D_pincode)
                           top_transaction_data["Transaction_Count"].append(T_count)
                           top_transaction_data["Transaction_Amount"].append(T_Amount)

                    


        df5=pd.DataFrame(top_transaction_data)
        return df5

Dataframe_top_Transaction=create_top_transaction_df()

In [ ]:
#6)To create_top_user Dataframe
def create_top_user_df():

            path="C:/Users/admin pc/Desktop/phonepe_git/data/top/user/country/india/state/"
            top_user_state=os.listdir(path)

            top_user_data={'State':[], 'Year':[],'Quarter':[],'District_pincode':[], 'Registered_Users':[]}

            for item1 in top_user_state:
                path1=path+item1+"/"
                top_user_year=os.listdir(path1)
                for item2 in top_user_year:
                    path2=path1+item2+"/"
                    json_list=os.listdir(path2)
                    for item3 in json_list:
                        path3=path2+item3
                        
                        read_json=open(path3,"r")   
                        json_file=json.load(read_json)

                        for item4 in json_file["data"]["pincodes"]:
                            D_pincode=item4["name"]
                            R_users=item4["registeredUsers"]
                            top_user_data["State"].append(item1)
                            top_user_data["Year"].append(item2)
                            top_user_data["Quarter"].append(int(item3.strip(".json")))
                            top_user_data["District_pincode"].append(D_pincode)
                            top_user_data["Registered_Users"].append(R_users)


            df6=pd.DataFrame(top_user_data)
            return df6

Dataframe_top_User=create_top_user_df()

In [ ]:
#Next step is cleaning process,change the string structure of "state" column of all dataframes

In [ ]:


Dataframe_aggregated_transaction["State"]=Dataframe_aggregated_transaction["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Dataframe_aggregated_transaction['State']=Dataframe_aggregated_transaction['State'].str.title()
Dataframe_aggregated_transaction['State']=Dataframe_aggregated_transaction["State"].str.replace("Dadra-&-Nagar-Haveli-&-Daman-&-Diu","Dadra and Nagar Haveli and Daman and Diu")
Dataframe_aggregated_transaction["State"]=Dataframe_aggregated_transaction["State"].str.replace("-"," ")
           

Dataframe_aggregated_user["State"]=Dataframe_aggregated_user["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Dataframe_aggregated_user['State']=Dataframe_aggregated_user['State'].str.title()
Dataframe_aggregated_user['State']=Dataframe_aggregated_user["State"].str.replace("Dadra-&-Nagar-Haveli-&-Daman-&-Diu","Dadra and Nagar Haveli and Daman and Diu")
Dataframe_aggregated_user["State"]=Dataframe_aggregated_user["State"].str.replace("-"," ")           


Dataframe_map_transaction["State"]=Dataframe_map_transaction["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Dataframe_map_transaction['State']=Dataframe_map_transaction['State'].str.title()
Dataframe_map_transaction['State']=Dataframe_map_transaction["State"].str.replace("Dadra-&-Nagar-Haveli-&-Daman-&-Diu","Dadra and Nagar Haveli and Daman and Diu")
Dataframe_map_transaction["State"]=Dataframe_map_transaction["State"].str.replace("-"," ")
Dataframe_map_transaction
                

Dataframe_map_user["State"]=Dataframe_map_user["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Dataframe_map_user['State']=Dataframe_map_user['State'].str.title()
Dataframe_map_user['State']=Dataframe_map_user["State"].str.replace("Dadra-&-Nagar-Haveli-&-Daman-&-Diu","Dadra and Nagar Haveli and Daman and Diu")
Dataframe_map_user["State"]=Dataframe_map_user["State"].str.replace("-"," ")
                                
                



Dataframe_top_Transaction["State"]=Dataframe_top_Transaction["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Dataframe_top_Transaction["State"]=Dataframe_top_Transaction["State"].str.replace("-"," ")
Dataframe_top_Transaction['State']=Dataframe_top_Transaction['State'].str.title()
Dataframe_top_Transaction['State']=Dataframe_top_Transaction["State"].str.replace("Dadra-&-Nagar-Haveli-&-Daman-&-Diu","Dadra and Nagar Haveli and Daman and Diu")




Dataframe_top_User["State"]=Dataframe_top_User["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Dataframe_top_User['State']=Dataframe_top_User['State'].str.title()
Dataframe_top_User['State']=Dataframe_top_User["State"].str.replace("Dadra-&-Nagar-Haveli-&-Daman-&-Diu","Dadra and Nagar Haveli and Daman and Diu")
Dataframe_top_User["State"]=Dataframe_top_User["State"].str.replace("-"," ")

In [ ]:
#To  create connection and database(project2sql) to sql for storing collected data

In [ ]:
#to conert dataframes to sql tables
myconnection1= pymysql.connect(host = '127.0.0.1',user='root',passwd='admin@123')
cur = myconnection1.cursor()
cur.execute("create database if not exists project2sql")

myconnection = pymysql.connect(host = '127.0.0.1',user='root',passwd='admin@123',database = "project2sql")
cur = myconnection.cursor()

In [ ]:
#Now i am going to create tables in SQL to store the data in Dataframes in  table format

In [ ]:
def create_table():
        cur.execute("create table if not exists Table_aggregated_transaction(State varchar(50),Year int(10),Quater int(10),Transaction_Type varchar(250),Transaction_Count bigint,Transaction_Amount bigint)")


        cur.execute("create table if not exists Table_aggregated_user(State varchar(50),Year int(10),Quater int(10),Brand varchar(100),User_Count int(200),User_Percentage int(100))")



        cur.execute("create table if not exists Table_map_transaction(State varchar(50),Year int(10),Quater int(10),District_Name varchar(100),Transaction_Count bigint,Transaction_Amount bigint)")



        cur.execute("create table if not exists Table_map_user(State varchar(50),Year int(10),Quater int(10),District_Name varchar(100),Registered_Users bigint,No_of_apps_Open int(200))")

        cur.execute("create table if not exists Table_top_transaction(State varchar(50),Year int(10),Quater int(10),District_pincode int(100),Transaction_Count bigint,Transaction_Amount bigint)")

        cur.execute("create table if not exists Table_top_user(State varchar(50),Year int(10),Quater int(10),District_pincode int(100),Registered_Users bigint)")

#create_table()

In [ ]:
#To insert values to the corresponding tables created in sql

In [ ]:
def insert_value1():
            insert1='''insert into Table_aggregated_transaction(State,Year,Quater,Transaction_Type,Transaction_Count,Transaction_Amount)  
                                                                                                    values(%s,%s,%s,%s,%s,%s)'''

            values_1=Dataframe_aggregated_transaction.values.tolist()
                                                
            try:
                cur.executemany(insert1,values_1)
                myconnection.commit()
            except:
                print("values not inserted")

insert_value1()

In [ ]:
def insert_value2():
            insert1='''insert into Table_aggregated_user(State,Year,Quater,Brand,User_Count,User_Percentage)  
                                                                                                    values(%s,%s,%s,%s,%s,%s)'''

            values_1=Dataframe_aggregated_user.values.tolist()
                                                
            try:
                cur.executemany(insert1,values_1)
                myconnection.commit()
            except:
                print("values not inserted")

insert_value2()

In [ ]:
def insert_value3():
            for index,row in Dataframe_map_transaction.iterrows():
                insert='''insert into Table_map_transaction(State,Year,Quater,District_Name,Transaction_Count,Transaction_Amount)  
                                                                                        values(%s,%s,%s,%s,%s,%s)'''
                values=(row['State'],
                        row['Year'],
                        row['Quater'],
                        row['District_Name'],
                        row['Transaction_Count'],
                        row['Transaction_Amount'])
                try:
                    cur.execute(insert,values)
                    myconnection.commit()
                except Exception as e:
                            print("values not inserted",e)

insert_value3()

In [ ]:
def insert_value4():
                for index,row in Dataframe_map_user.iterrows():
                insert='''insert into Table_map_user(State,Year,Quater,District_Name,Registered_Users,No_of_apps_Open)  
                                                                                        values(%s,%s,%s,%s,%s,%s)'''
                values=(row['State'],
                        row['Year'],
                        row['Quater'],
                        row['District_Name'],
                        row['Registered_Users'],
                        row['No_of_apps_Open'])
                try:
                    cur.execute(insert,values)
                    myconnection.commit()
                except:
                                        print("values not inserted")

insert_value4()

In [ ]:
def insert_value5():
            insert1_='''insert into Table_top_Transaction(State,Year,Quater,District_pincode,Transaction_Count,Transaction_Amount)  
                                                                                                    values(%s,%s,%s,%s,%s,%s)'''

            values1_=Dataframe_top_Transaction.values.tolist()
                                                
            try:
                cur.executemany(insert1_,values1_)
                myconnection.commit()
            except Exception as e:
                print("values not inserted",e)

insert_value5()

In [ ]:
def insert_value6():
            insert2_='''insert into Table_top_user(State,Year,Quater,District_pincode,Registered_Users)  
                                                                                                    values(%s,%s,%s,%s,%s)'''

            values2_=Dataframe_top_User.values.tolist()
                                                
            try:
                cur.executemany(insert2_,values2_)
                myconnection.commit()
            except Exception as e:
                print("values not inserted",e)

insert_value6()

In [ ]:
#Now i have stoted Data as 6 Tables in SQL,Next have to display the collected data visulization using plotly and have to display the output on Steamlit